sudo: false
arch:
  - amd64
  - ppc64le
language: node_js
node_js:
  - "8"
  - "10"
  - "12"
  - "14"
  - lts/*
  - current
env:
  matrix:
    - TEST_SUITE=unit
matrix:
  include:
    - node_js: "6"
      env: TEST_SUITE=lint
    - node_js: "6"
      arch: ppc64le
      env: TEST_SUITE=lint
script: npm run-script $TEST_SUITE
